import { IApprovalRequest } from "@/interface/approval";

export const fieldNameMap: Record<string, Record<string, string>> = {
  USER: {
    id: "ইউজার আইডি",
    name: "ইউজারের নাম",
    username: "ইউজারনেম",
    role: "ইউজারের ভূমিকা",
    password: "পাসওয়ার্ড",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটার আইডি",
  },

  LOGIN_HISTORY: {
    id: "লগইন হিস্টোরি আইডি",
    type: "লগইনের ধরন",
    device: "ডিভাইস",
    browser: "ব্রাউজার",
    ipAddress: "আইপি ঠিকানা",
    userId: "ইউজার",
    createdAt: "লগইনের সময়",
  },

  CLASS_RATE: {
    id: "শ্রেণী ও রেট আইডি",
    classType: "শ্রেণির ধরন",
    className: "শ্রেণির নাম",
    rate: "বিক্রয় রেট",
    advanceRate: "অগ্রিম রেট",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    isDeleted: "ডিলেট স্ট্যাটাস",
    vataId: "ভাটার আইডি",
    deleteStatus: "ডিলেট অনুমোদন স্ট্যাটাস",
    updateStatus: "আপডেট অনুমোদন স্ট্যাটাস",
  },

  CHALLAN: {
    id: "চালান আইডি",
    serial: "চালান নম্বর",
    chalanType: "চালানের ধরন",
    deliveryDate: "ডেলিভারির তারিখ",
    challanDate: "চালানের তারিখ",
    duePaymentDate: "বাকি পরিশোধের তারিখ",
    deliverySeason: "ডেলিভারি মৌসুম",
    note: "চালানের নোট",
    productPrice: "পণ্যের মূল্য",
    discount: "ডিসকাউন্ট",
    carRent: "গাড়ি ভাড়া",
    totalPrice: "মোট মূল্য",
    cash: "নগদ পরিশোধ",
    due: "বাকি",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    customerId: "কাস্টমার",
    vataId: "ভাটা",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdById: "তৈরি করেছেন",
    seasonId: "মৌসুম",
  },

  CHALLAN_ITEM: {
    id: "চালান আইটেম আইডি",
    class: "ইটের শ্রেণি",
    rate: "রেট",
    quantity: "চালানের পরিমাণ",
    delivered: "ডেলিভারি দেওয়া পরিমাণ",
    price: "মূল্য",
    challanId: "চালান",
    deliveryDate: "ডেলিভারির তারিখ",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    isDeleted: "ডিলেট স্ট্যাটাস",
  },

  CUSTOMER: {
    id: "কাস্টমার আইডি",
    customerCode: "কাস্টমার কোড",
    name: "কাস্টমারের নাম",
    address: "কাস্টমারের ঠিকানা",
    phoneNumber: "কাস্টমারের মোবাইল নম্বর",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    isDeleted: "ডিলেট স্ট্যাটাস",
    nextPaymentDate: "পরবর্তী পেমেন্টের তারিখ",
    note: "কাস্টমারের নোট",
    vataId: "ভাটা",
  },

  CUSTOMER_DUE: {
    id: "কাস্টমার বাকি আইডি",
    customerId: "কাস্টমার",
    seasonId: "মৌসুম",
    challanId: "চালান",
    totalAmount: "মোট টাকা",
    paidAmount: "পরিশোধিত টাকা",
    dueAmount: "বকেয়া টাকা",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  DELIVERY: {
    id: "ডেলিভারি আইডি",
    deliveryDate: "ডেলিভারির তারিখ",
    deliveryNo: "ডেলিভারি নম্বর",
    nextDeliveryDate: "পরবর্তী ডেলিভারির তারিখ",
    quantity: "ডেলিভারির পরিমাণ",
    deliveryReceived: "গ্রহণ করা পরিমাণ",
    class: "ইটের শ্রেণি",
    deliveryRemaining: "অবশিষ্ট ডেলিভারি",
    carNo: "গাড়ির নম্বর",
    lastDelivered: "সর্বশেষ ডেলিভারি",
    status: "ডেলিভারি স্ট্যাটাস",
    carRent: "গাড়ি ভাড়া",
    invoiceId: "চালান",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    season: "মৌসুম",
    deliveryById: "ডেলিভারি দিয়েছেন",
    driverId: "ড্রাইভার",
  },

  DELIVERY_STATUS_TIME: {
    id: "ডেলিভারি স্ট্যাটাস টাইম আইডি",
    deliveryId: "ডেলিভারি",
    pendingTime: "অপেক্ষমাণ হওয়ার সময়",
    processingTime: "প্রসেসিং হওয়ার সময়",
    deliveredTime: "ডেলিভারি সম্পন্ন হওয়ার সময়",
    cancelTime: "বাতিল হওয়ার সময়",
  },

  DUE: {
    id: "বাকি আদায় আইডি",
    due: "আগের বাকি",
    collect: "আদায়ের পরিমাণ",
    newDue: "নতুন বাকি",
    nextDate: "পরবর্তী পেমেন্টের তারিখ",
    customerId: "কাস্টমার",
    seasonId: "মৌসুম",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  LEDGER: {
    id: "লেজার আইডি",
    name: "লেজারের নাম",
    serial: "লেজার নম্বর",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    parentId: "মূল লেজার",
    rate: "লেজার রেট",
    quantity: "লেজার পরিমাণ",
    isDeleted: "ডিলেট স্ট্যাটাস",
    vataId: "ভাটা",
    seasonId: "মৌসুম",
    phoneNumber: "মোবাইল নম্বর",
    startDate: "শুরুর তারিখ",
    salary: "বেতন",
    weeklyFood: "সাপ্তাহিক খাবার",
    openingBalance: "প্রারম্ভিক ব্যালেন্স",
    openingBalanceType: "প্রারম্ভিক ব্যালেন্সের ধরন",
  },

  PAYMENT: {
    id: "পেমেন্ট আইডি",
    serial: "পেমেন্ট নম্বর",
    quantity: "পেমেন্টের পরিমাণ",
    cutting: "কাটিং",
    payment: "পরিশোধের পরিমাণ",
    ledgerId: "লেজার",
    vataId: "ভাটা",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    document: "ডকুমেন্ট",
    paymentDetails: "পেমেন্টের বিবরণ",
    paymentDifference: "পেমেন্টের পার্থক্য",
    paymentType: "পেমেন্টের ধরন",
    rate: "পেমেন্ট রেট",
    address: "ঠিকানা",
    totalBill: "মোট বিল",
    isDeleted: "ডিলেট স্ট্যাটাস",
    paymentDate: "পেমেন্টের তারিখ",
  },

  CASH: {
    id: "ক্যাশ আইডি",
    type: "ক্যাশ লেনদেনের ধরন",
    source: "ক্যাশের উৎস",
    description: "ক্যাশের বিবরণ",
    amount: "ক্যাশের পরিমাণ",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
    seasonId: "মৌসুম",
  },

  ROUND: {
    id: "রাউন্ড আইডি",
    name: "রাউন্ডের নাম",
    vataId: "ভাটা",
    seasonId: "মৌসুম",
  },

  LOAD_INFO: {
    id: "লোড আইডি",
    date: "লোডের তারিখ",
    roundId: "রাউন্ড",
    quantity: "লোডের পরিমাণ",
    loadType: "লোডের ধরন",
    classId: "ইটের শ্রেণি",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  UNLOAD: {
    id: "আনলোড আইডি",
    date: "আনলোডের তারিখ",
    roundId: "রাউন্ড",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  UNLOAD_ITEM: {
    id: "আনলোড আইটেম আইডি",
    unloadId: "আনলোড",
    classId: "ইটের শ্রেণি",
    quantity: "আনলোডের পরিমাণ",
    damaged: "ক্ষতিগ্রস্ত পরিমাণ",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  BRICK_STOCK_SUMMARY: {
    id: "স্টক সামারি আইডি",
    vataId: "ভাটা",
    rawBrick: "কাঁচা ইট",
    fieldBrick: "মাঠের ইট",
    stockBrick: "স্টকের ইট",
    chulliBrick: "চুল্লির ইট",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  STOCK: {
    id: "স্টক আইডি",
    class: "ইটের শ্রেণি",
    stockIn: "স্টকে প্রবেশ",
    stockOut: "স্টক থেকে বের",
    description: "স্টকের বিবরণ",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    createdById: "তৈরি করেছেন",
    seasonId: "মৌসুম",
    vataId: "ভাটা",
  },

  GOODS_STOCK_CATEGORY: {
    id: "পণ্য ক্যাটাগরি আইডি",
    name: "ক্যাটাগরির নাম",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
    isDeleted: "ডিলেট স্ট্যাটাস",
  },

  GOODS_STOCK: {
    id: "পণ্য স্টক আইডি",
    name: "পণ্যের নাম",
    shop: "দোকানের নাম",
    quantity: "পণ্যের পরিমাণ",
    price: "পণ্যের মূল্য",
    warranty: "ওয়ারেন্টির তারিখ",
    image: "পণ্যের ছবি",
    categoryId: "পণ্য ক্যাটাগরি",
    vataId: "ভাটা",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  GOODS_ISSUE: {
    id: "পণ্য ইস্যু আইডি",
    name: "পণ্যের নাম",
    location: "ব্যবহারের স্থান",
    quantity: "ইস্যু করা পরিমাণ",
    date: "ইস্যুর তারিখ",
    image: "পণ্যের ছবি",
    goodId: "পণ্য",
    note: "ইস্যুর নোট",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  GOOD_HISTORY_LOG: {
    id: "পণ্য হিস্টোরি আইডি",
    type: "হিস্টোরির ধরন",
    description: "হিস্টোরির বিবরণ",
    receiveBy: "গ্রহণ করেছেন",
    quantity: "পরিমাণ",
    returnBy: "ফেরত দিয়েছেন",
    goodId: "পণ্য",
    date: "তারিখ",
    damage: "ক্ষতিগ্রস্ত পরিমাণ",
    lost: "হারানো পরিমাণ",
    okay: "ভালো পরিমাণ",
    image: "ছবি",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  GOODS_LOSS: {
    id: "পণ্য ক্ষতি আইডি",
    goodId: "পণ্য",
    quantity: "ক্ষতির পরিমাণ",
    type: "ক্ষতির ধরন",
    lossAmount: "ক্ষতির টাকা",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  DOCUMENT: {
    id: "ডকুমেন্ট আইডি",
    name: "ডকুমেন্টের নাম",
    type: "ডকুমেন্টের ধরন",
    parentId: "মূল ফোল্ডার",
    fileUrl: "ফাইল URL",
    fileKey: "ফাইল কী",
    mimeType: "ফাইলের MIME টাইপ",
    size: "ফাইলের সাইজ",
    extension: "ফাইল এক্সটেনশন",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
  },

  CAR_RENT: {
    id: "গাড়ি ভাড়া আইডি",
    address: "ঠিকানা",
    area: "এলাকা",
    rent: "ভাড়ার পরিমাণ",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
  },

  PRODUCT: {
    id: "পণ্য আইডি",
    productName: "পণ্যের নাম",
    category: "পণ্যের ক্যাটাগরি",
    shop: "দোকানের নাম",
    quantity: "পণ্যের পরিমাণ",
    price: "পণ্যের মূল্য",
    productImage: "পণ্যের ছবি",
    warranty: "ওয়ারেন্টির তারিখ",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
  },

  TASK: {
    id: "টাস্ক আইডি",
    description: "টাস্কের বিবরণ",
    userId: "টাস্কের দায়িত্বপ্রাপ্ত ইউজার",
    date: "টাস্কের তারিখ",
    repeat: "পুনরাবৃত্তি",
    status: "টাস্কের স্ট্যাটাস",
    vataId: "ভাটা",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  RECEIVABLE_PAYABLE: {
    id: "দেনা-পাওনা আইডি",
    transactionType: "লেনদেনের ধরন",
    amount: "মোট টাকা",
    currentAmount: "বর্তমান টাকা",
    name: "ব্যক্তির নাম",
    phone: "মোবাইল নম্বর",
    address: "ঠিকানা",
    transactionDate: "লেনদেনের তারিখ",
    paymentDate: "পেমেন্টের তারিখ",
    witnessOne: "সাক্ষী ১",
    witnessTwo: "সাক্ষী ২",
    description: "লেনদেনের বিবরণ",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
  },

  RECEIVABLE_PAYABLE_TRANSACTION: {
    id: "দেনা-পাওনা ট্রানজেকশন আইডি",
    receivablePayableId: "দেনা-পাওনা",
    type: "লেনদেনের ধরন",
    amount: "লেনদেনের পরিমাণ",
    transactionDate: "লেনদেনের তারিখ",
    remaining: "অবশিষ্ট টাকা",
    description: "লেনদেনের বিবরণ",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
  },

  CONTACT: {
    id: "কন্টাক্ট আইডি",
    name: "কন্টাক্টের নাম",
    address: "কন্টাক্টের ঠিকানা",
    occupation: "পেশা",
    phone: "মোবাইল নম্বর",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
  },

  WEATHER: {
    id: "ওয়েদার আইডি",
    linkOne: "ওয়েদার লিংক ১",
    linkTwo: "ওয়েদার লিংক ২",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
  },

  VATA: {
    id: "ভাটা আইডি",
    vataId: "ভাটার ইউনিক আইডি",
    nameEnglish: "ভাটার ইংরেজি নাম",
    nameBangla: "ভাটার বাংলা নাম",
    additionalAddress: "অতিরিক্ত ঠিকানা",
    shortDescription: "সংক্ষিপ্ত বিবরণ",
    address: "ভাটার ঠিকানা",
    ownerName: "মালিকের নাম",
    ownerPhoneNumber: "মালিকের মোবাইল নম্বর",
    shortForm: "ভাটার সংক্ষিপ্ত নাম",
    challanManagerPhoneNumber: "চালান ম্যানেজারের মোবাইল নম্বর",
    challanPersonOneName: "চালান ব্যক্তি ১-এর নাম",
    challanPersonOnePhoneNumber: "চালান ব্যক্তি ১-এর মোবাইল নম্বর",
    challanPersonTwoName: "চালান ব্যক্তি ২-এর নাম",
    challanPersonTwoPhoneNumber: "চালান ব্যক্তি ২-এর মোবাইল নম্বর",
    nextPaymentDate: "পরবর্তী পেমেন্টের তারিখ",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    subdomain: "সাবডোমেইন",
    status: "ভাটার স্ট্যাটাস",
    subscriptionPlanId: "সাবস্ক্রিপশন প্ল্যান",
    subscriptionStart: "সাবস্ক্রিপশন শুরুর তারিখ",
    subscriptionEnd: "সাবস্ক্রিপশন শেষের তারিখ",
  },

  SUBSCRIPTION_PLAN: {
    id: "সাবস্ক্রিপশন প্ল্যান আইডি",
    name: "প্ল্যানের নাম",
    type: "প্ল্যানের ধরন",
    description: "প্ল্যানের বিবরণ",
    price: "প্ল্যানের মূল্য",
    billingCycle: "বিলিং সাইকেল",
    features: "প্ল্যানের ফিচার",
    maxUsers: "সর্বোচ্চ ইউজার",
    maxStorage: "সর্বোচ্চ স্টোরেজ",
    maxTasks: "সর্বোচ্চ টাস্ক",
    maxInvoices: "সর্বোচ্চ ইনভয়েস",
    maxSms: "সর্বোচ্চ SMS",
    isActive: "প্ল্যান সক্রিয়",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  SUBSCRIPTION_PAYMENT: {
    id: "সাবস্ক্রিপশন পেমেন্ট আইডি",
    vataId: "ভাটা",
    subscriptionPlanId: "সাবস্ক্রিপশন প্ল্যান",
    startDate: "সাবস্ক্রিপশনের শুরুর তারিখ",
    endDate: "সাবস্ক্রিপশনের শেষের তারিখ",
    amount: "পেমেন্টের পরিমাণ",
    status: "পেমেন্ট স্ট্যাটাস",
    paidAt: "পেমেন্টের সময়",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    transactionId: "ট্রানজেকশন আইডি",
    phoneNumber: "পেমেন্টের মোবাইল নম্বর",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  SEASON: {
    id: "মৌসুম আইডি",
    vataId: "ভাটা",
    name: "মৌসুমের নাম",
    startDate: "মৌসুম শুরুর তারিখ",
    endDate: "মৌসুম শেষের তারিখ",
    isActive: "মৌসুম সক্রিয়",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  DRIVER: {
    id: "ড্রাইভার আইডি",
    name: "ড্রাইভারের নাম",
    PhoneNumber: "ড্রাইভারের মোবাইল নম্বর",
    salary: "ড্রাইভারের বেতন",
    vataId: "ভাটা",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  VATA_CAR: {
    id: "গাড়ি আইডি",
    vataId: "ভাটা",
    carNo: "গাড়ির নম্বর",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  CAR_INCOME_DELIVERY: {
    id: "গাড়ি ইনকাম ডেলিভারি আইডি",
    amount: "আয়ের পরিমাণ",
    driverId: "ড্রাইভার",
    deliveryId: "ডেলিভারি",
    carId: "গাড়ি",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  SMS_SETTING: {
    id: "SMS সেটিং আইডি",
    ratePerSms: "প্রতি SMS-এর মূল্য",
    bkash: "বিকাশ নম্বর",
    rocket: "রকেট নম্বর",
    nogod: "নগদ নম্বর",
    isActive: "SMS সেটিং সক্রিয়",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  SMS_WALLET: {
    id: "SMS ওয়ালেট আইডি",
    vataId: "ভাটা",
    balance: "বর্তমান ব্যালেন্স",
    totalPurchased: "মোট কেনা SMS",
    totalUsed: "মোট ব্যবহৃত SMS",
    currentRate: "বর্তমান SMS রেট",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  SMS_RECHARGE_HISTORY: {
    id: "SMS রিচার্জ আইডি",
    vataId: "ভাটা",
    smsQuantity: "SMS-এর সংখ্যা",
    ratePerSms: "প্রতি SMS-এর মূল্য",
    totalAmount: "মোট টাকা",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    transactionId: "ট্রানজেকশন আইডি",
    phoneNumber: "পেমেন্টের মোবাইল নম্বর",
    type: "পেমেন্টের ধরন",
    status: "রিচার্জ স্ট্যাটাস",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  VATA_SMS_SETTINGS: {
    id: "ভাটা SMS সেটিং আইডি",
    newInvoice: "নতুন ইনভয়েস SMS",
    updateInvoice: "ইনভয়েস আপডেট SMS",
    deleteInvoice: "ইনভয়েস ডিলেট SMS",
    newDelivery: "নতুন ডেলিভারি SMS",
    newDueCollection: "নতুন বাকি আদায় SMS",
    deuCollectionUpdate: "বাকি আদায় আপডেট SMS",
    vataId: "ভাটা",
  },

  SMS_LOG: {
    id: "SMS লগ আইডি",
    vataId: "ভাটা",
    phoneNumber: "SMS প্রাপকের মোবাইল নম্বর",
    message: "SMS মেসেজ",
    status: "SMS স্ট্যাটাস",
    sendBy: "SMS পাঠিয়েছেন",
    cost: "SMS খরচ",
    sentAt: "SMS পাঠানোর সময়",
  },

  NOTE: {
    id: "নোট আইডি",
    message: "নোট",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  NOTIFICATION: {
    id: "নোটিফিকেশন আইডি",
    title: "নোটিফিকেশনের শিরোনাম",
    message: "নোটিফিকেশন মেসেজ",
    path: "নোটিফিকেশন পাথ",
    type: "নোটিফিকেশনের ধরন",
    isRead: "পড়া হয়েছে",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
    vataId: "ভাটা",
    seasonId: "মৌসুম",
  },

  FAQ: {
    id: "FAQ আইডি",
    title: "FAQ-এর শিরোনাম",
    description: "FAQ-এর বিবরণ",
    createdAt: "তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  ABOUT_US: {
    id: "About Us আইডি",
    description: "About Us-এর বিবরণ",
  },

  HELP_LINE: {
    id: "হেল্পলাইন আইডি",
    phoneNumber: "হেল্পলাইন নম্বর",
    website: "ওয়েবসাইট",
    email: "ইমেইল",
  },

  YOUTUBE_LINK: {
    id: "YouTube লিংক আইডি",
    link: "YouTube লিংক",
  },

  DATABASE_BACKUP_PERMISSION: {
    id: "ব্যাকআপ পারমিশন আইডি",
    type: "ব্যাকআপের ধরন",
  },

  DATABASE_BACKUP: {
    id: "ডাটাবেজ ব্যাকআপ আইডি",
    fileName: "ব্যাকআপ ফাইলের নাম",
    filePath: "ব্যাকআপ ফাইলের পাথ",
    fileSize: "ব্যাকআপ ফাইলের সাইজ",
    type: "ব্যাকআপের ধরন",
    tableCount: "টেবিলের সংখ্যা",
    totalRowCount: "মোট রো সংখ্যা",
    tableRowCounts: "প্রতিটি টেবিলের রো সংখ্যা",
    createdAt: "ব্যাকআপ তৈরির সময়",
  },

  APPROVAL_REQUEST: {
    id: "অনুমোদন অনুরোধ আইডি",
    vataId: "ভাটা",
    requestedById: "অনুরোধকারী",
    action: "অনুমোদনের অ্যাকশন",
    module: "মডিউল",
    targetId: "টার্গেট রেকর্ড",
    oldData: "পুরোনো তথ্য",
    newData: "বর্তমান তথ্য",
    status: "অনুমোদনের স্ট্যাটাস",
    isDeleted: "ডিলেট স্ট্যাটাস",
    reviewedAt: "রিভিউয়ের সময়",
    createdAt: "অনুরোধ তৈরির সময়",
    updatedAt: "আপডেটের সময়",
  },

  ACTIVITY_LOG: {
    id: "অ্যাক্টিভিটি লগ আইডি",
    vataId: "ভাটা",
    userId: "কাজটি করেছেন",
    module: "মডিউল",
    action: "অ্যাকশন",
    targetId: "টার্গেট রেকর্ড",
    description: "অ্যাক্টিভিটির বিবরণ",
    isDeleted: "ডিলেট স্ট্যাটাস",
    createdAt: "অ্যাক্টিভিটির সময়",
  },
};

export const getModuleName = (module: IApprovalRequest["module"]) => {
  const moduleNames: Record<string, string> = {
    USER: "ইউজার",
    LOGIN_HISTORY: "লগইন ইতিহাস",
    CLASS_RATE: "শ্রেণি ও রেট",
    CHALLAN: "চালান",
    CHALLAN_ITEM: "চালানের পণ্য",
    CUSTOMER: "কাস্টমার",
    CUSTOMER_DUE: "কাস্টমারের বাকি",
    DELIVERY: "ডেলিভারি",
    DELIVERY_STATUS_TIME: "ডেলিভারি স্ট্যাটাস",
    DUE: "বাকি আদায়",
    LEDGER: "লেজার",
    PAYMENT: "পেমেন্ট",
    CASH: "ক্যাশ",
    ROUND: "রাউন্ড",
    LOAD_INFO: "লোড তথ্য",
    UNLOAD: "আনলোড",
    UNLOAD_ITEM: "আনলোড তথ্য",
    BRICK_STOCK_SUMMARY: "ইটের স্টক সারাংশ",
    STOCK: "স্টক",
    GOODS_STOCK_CATEGORY: "পণ্য স্টক ক্যাটাগরি",
    GOODS_STOCK: "পণ্য স্টক",
    GOODS_ISSUE: "পণ্য ইস্যু",
    GOOD_HISTORY_LOG: "পণ্যের ইতিহাস",
    GOODS_LOSS: "পণ্যের ক্ষতি",
    DOCUMENT: "ডকুমেন্ট",
    CAR_RENT: "গাড়ি ভাড়া",
    PRODUCT: "পণ্য",
    TASK: "টাস্ক",
    RECEIVABLE_PAYABLE: "পাওনা-দেনা",
    RECEIVABLE_PAYABLE_TRANSACTION: "পাওনা-দেনার লেনদেন",
    CONTACT: "যোগাযোগ",
    WEATHER: "আবহাওয়া",
    VATA: "ভাটা",
    SUBSCRIPTION_PLAN: "সাবস্ক্রিপশন প্ল্যান",
    SUBSCRIPTION_PAYMENT: "সাবস্ক্রিপশন পেমেন্ট",
    SEASON: "সিজন",
    DRIVER: "ড্রাইভার",
    VATA_CAR: "ভাটার গাড়ি",
    CAR_INCOME_DELIVERY: "গাড়ির আয়",
    SMS_SETTING: "SMS সেটিংস",
    SMS_WALLET: "SMS ওয়ালেট",
    SMS_RECHARGE_HISTORY: "SMS রিচার্জ ইতিহাস",
    VATA_SMS_SETTINGS: "ভাটার SMS সেটিংস",
    SMS_LOG: "SMS লগ",
    NOTE: "নোট",
    NOTIFICATION: "নোটিফিকেশন",
    FAQ: "FAQ",
    ABOUT_US: "আমাদের সম্পর্কে",
    HELP_LINE: "হেল্পলাইন",
    YOUTUBE_LINK: "YouTube লিংক",
    DATABASE_BACKUP_PERMISSION: "ডাটাবেজ ব্যাকআপ অনুমতি",
    DATABASE_BACKUP: "ডাটাবেজ ব্যাকআপ",
    APPROVAL_REQUEST: "অনুমোদনের অনুরোধ",
    ACTIVITY_LOG: "অ্যাক্টিভিটি লগ",
  };

  return moduleNames[module] || module;
};
